# Generated by Django 2.1.2 on 2018-10-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_motives'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Motives',
            new_name='Motive',
        ),
    ]
